parameters:
    viteloge_frontend.component.helper.ad.class: Viteloge\FrontendBundle\Component\Helper\AdHelper
    viteloge_frontend.twig.extension.class: Viteloge\FrontendBundle\Twig\VitelogeFrontendExtension
    viteloge_frontend.pagerfanta.view.viteloge.class: Viteloge\FrontendBundle\Pagerfanta\View\VitelogeView
    viteloge_frontend.pagerfanta.view.viteloge_translated.class: Viteloge\FrontendBundle\Pagerfanta\View\VitelogeViewTranslated
services:
    viteloge_frontend.ad_helper:
        class: "%viteloge_frontend.component.helper.ad.class%"
        arguments: ["@translator"]
    viteloge_frontend.twig.extension:
        class: "%viteloge_frontend.twig.extension.class%"
        arguments: ["@service_container","@request_stack"]
        tags:
            - { name: twig.extension, priority: 255 }
    pagerfanta.view.viteloge:
        class: "%viteloge_frontend.pagerfanta.view.viteloge.class%"
        public: false
        tags: [{ name: pagerfanta.view, alias: pager_viteloge}]
    pagerfanta.view.viteloge_translated:
        class: "%viteloge_frontend.pagerfanta.view.viteloge_translated.class%"
        arguments:
            - "@pagerfanta.view.viteloge"
            - "@translator"
        public: false
        tags: [{ name: pagerfanta.view, alias: pager_viteloge_translated }]


