parameters:
    viteloge_twig.controller.exception.class: Viteloge\FrontendBundle\Controller\ExceptionController
    viteloge_frontend.form.type.usersearch.class: Viteloge\FrontendBundle\Form\Type\UserSearchType
    viteloge_frontend.form.type.websearch.class: Viteloge\FrontendBundle\Form\Type\WebSearchType
    viteloge_frontend.component.helper.ad.class: Viteloge\FrontendBundle\Component\Helper\AdHelper
    viteloge_frontend.twig.extension.class: Viteloge\FrontendBundle\Twig\VitelogeFrontendExtension
    viteloge_frontend.pagerfanta.view.viteloge.class: Viteloge\FrontendBundle\Pagerfanta\View\VitelogeView
    viteloge_frontend.pagerfanta.view.viteloge_translated.class: Viteloge\FrontendBundle\Pagerfanta\View\VitelogeViewTranslated
    viteloge_frontend.eventlistener.sitemap.class: Viteloge\FrontendBundle\EventListener\SitemapListener
    viteloge_frontend.eventlistener.websearch.class: Viteloge\FrontendBundle\EventListener\WebSearchListener
    viteloge_frontend.eventlistener.message.class: Viteloge\FrontendBundle\EventListener\MessageListener
    viteloge_frontend.services.class: Viteloge\FrontendBundle\Services\manageUser
    viteloge_frontend.services.cookies: Viteloge\FrontendBundle\Services\cookiesFactory
services:
    viteloge_twig.controller.exception:
        class: "%viteloge_twig.controller.exception.class%"
        arguments: ["@service_container", "%kernel.debug%"]
    viteloge_frontend.form.type.usersearch:
        class: "%viteloge_frontend.form.type.usersearch.class%"
        arguments: ["@security.token_storage", "@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: viteloge_frontend_usersearch }
    viteloge_frontend.form.type.websearch:
        class: "%viteloge_frontend.form.type.websearch.class%"
        arguments: ["@security.token_storage", "@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: viteloge_frontend_websearch }
    viteloge_frontend.ad_helper:
        class: "%viteloge_frontend.component.helper.ad.class%"
        arguments: ["@translator"]
    viteloge_frontend.twig.extension:
        class: "%viteloge_frontend.twig.extension.class%"
        arguments: ["@service_container","@request_stack"]
        tags:
            - { name: twig.extension, priority: 255 }
    pagerfanta.view.viteloge:
        class: "%viteloge_frontend.pagerfanta.view.viteloge.class%"
        public: false
        tags: [{ name: pagerfanta.view, alias: pager_viteloge}]
    pagerfanta.view.viteloge_translated:
        class: "%viteloge_frontend.pagerfanta.view.viteloge_translated.class%"
        arguments:
            - "@pagerfanta.view.viteloge"
            - "@translator"
        public: false
        tags: [{ name: pagerfanta.view, alias: pager_viteloge_translated }]
    viteloge_frontend_generate.user:
        class: "%viteloge_frontend.services.class%"
        arguments: ["@service_container","@security.token_storage", "@doctrine.orm.entity_manager"]
    viteloge_frontend_generate.cookies:
        class: "%viteloge_frontend.services.cookies%"
        arguments: ["@request_stack","@doctrine.orm.entity_manager"]
    viteloge_frontend.websearchlistener:
        class: "%viteloge_frontend.eventlistener.websearch.class%"
        arguments: ["@fos_elastica.manager"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    viteloge_frontend.messagelistener:
        class: "%viteloge_frontend.eventlistener.message.class%"
        tags:
            - { name: doctrine.event_listener, event: prePersist }




