imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata_seo.yml }
    - { resource: fos_elastica.yml }
    - { resource: fos_user.yml }
    - { resource: hwi_oauth.yml }
    - { resource: stof_doctrine_extensions.yml }
    - { resource: white_october_breadcrumbs.yml }
    - { resource: white_october_pagerfanta.yml }
    - { resource: jms_i18n_routing.yml }
    - { resource: doctrine_migrations.yml }
    - { resource: fos_js_routing.yml }
    - { resource: ewz_recaptcha.yml }
    - { resource: presta_sitemap.yml }
    - { resource: genemu_form.yml }


# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    account.section.rollout_settings:
        environment: "dev"
        enabled: true
        test_weight: 0.5 # proportion of people who se the new account section. i.e. 1 --> 100%


framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
        #remove debug bar
    #profiler:
        #collect: false

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes: ['VitelogeFrontendBundle:Form:fields.html.twig']
    globals:
        fos_csrf_provider: "@security.csrf.token_manager"
        domain: "%domain%"
        media_domain: "%media_domain%"
        ga_tracking: "%ga_tracking%"
        google_maps_api_key: "%google_maps_api_key%"
        adsense_publisher_id: "%adsense_publisher_id%"
        adsense_slots: "%adsense_slots%"
        adsense_slot_spec: "%adsense_slot_spec%"
        facebook_account: "%facebook_account%"
        facebook_client_id: "%facebook_client_id%"
        facebook_client_secret: "%facebook_client_secret%"
        facebook_app_version: "%facebook_app_version%"
        twitter_account: "%twitter_account%"
        #fos_csrf_provider: "@security.csrf.token_manager"

# Doctrine Configuration
doctrine:
    dbal:
        server_version: 5.6
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            enumtransaction: Viteloge\CoreBundle\Component\DBAL\EnumTransactionType
            stringy_simple_array: Viteloge\CoreBundle\Component\DBAL\StringifySimpleArrayType
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            numeric_functions:
                round: Viteloge\CoreBundle\Component\ORM\Query\Functions\Round
            string_functions:
                soundex: Viteloge\CoreBundle\Component\ORM\Query\Functions\Soundex
                md5: Viteloge\CoreBundle\Component\ORM\Query\Functions\Md5
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
