fos_js_routing:
    routes_to_expose: [ viteloge_insee_area_show, viteloge_frontend_ad_carousel, viteloge_frontend_prefer_favourite, viteloge_frontend_agency_phone, viteloge_frontend_agency_call,viteloge_frontend_agency_last_view,viteloge_frontend_message_ajax ]
