viteloge_estim:
    resource: "@VitelogeEstimationBundle/Resources/config/routing.yml"
    prefix:   /

viteloge_front:
    resource: "@VitelogeFrontendBundle/Resources/config/routing.yml"
    prefix:   /

viteloge_insee:
    resource: "@VitelogeInseeBundle/Resources/config/routing.yml"
    prefix:   /

viteloge_twig:
    resource: "@VitelogeTwigBundle/Resources/config/routing.yml"
    prefix:   /

viteloge_user:
    resource: "@VitelogeUserBundle/Resources/config/routing.yml"
    prefix:   /

viteloge_frontend:
    resource: "@VitelogeFrontendBundle/Resources/config/routing.yml"
    prefix:   /

viteloge_estimation:
    resource: "@VitelogeEstimationBundle/Resources/config/routing.yml"
    prefix:   /

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

viteloge_o_auth:
    resource: "@VitelogeOAuthBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

