parameters:
    twig.extension.text.class: Twig_Extensions_Extension_Text
    twig.extension.intl.class: Twig_Extensions_Extension_Intl

services:
    twig.text_extension:
        class: "%twig.extension.text.class%"
        tags:
            - name: twig.extension
    twig.extension.intl:
       class: "%twig.extension.intl.class%"
       tags:
           - { name: twig.extension }
    fos_user.doctrine_registry:
        alias: doctrine
