<?php

namespace Viteloge\CoreBundle\Repository {

    use Viteloge\CoreBundle\Component\ORM\EntityRepository;
    use Viteloge\InseeBundle\Entity\InseeCity;

    /**
     * CityDataRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class CityDataRepository extends EntityRepository {

        /**
         *
         */
        public function findByInseeCityId($id) {
            $cityData = null;
            $repository = $this->getEntityManager()->getRepository('VitelogeInseeBundle:InseeCity');
            $inseeCity = $repository->findOneById($id);
            if ($inseeCity instanceof InseeCity) {
                $cityData = $this->findByInseeCity($inseeCity);
            }
            return $cityData;
        }

    }

}
