<?php

namespace Viteloge\CoreBundle\Repository {

    use Viteloge\CoreBundle\Component\ORM\EntityRepository;

    /**
     * AccountRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class UserRepository extends EntityRepository {

    }

}
