<?php

namespace Viteloge\CoreBundle\SearchRepository {


    use Viteloge\CoreBundle\SearchEntity\Ad;
    use Viteloge\InseeBundle\Entity\InseeArea;
    use Doctrine\ORM\EntityManager;

    /**
     * AdRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class AdInsee {

        protected $em;

        public function __construct(EntityManager $em) {
            $this->em = $em;
        }



        /**
         *
         */
        public function getArea(Ad $ad) {
           $terms = array();
                foreach ($ad->getWhereArea() as $key => $id) {
                    $area = $this->em->getRepository('VitelogeInseeBundle:InseeArea')->find($id);
                    if ($area instanceof InseeArea) {
                        $keywords = explode(',', strtolower($area->getKeywords()));
                        $terms = array_merge($terms, array_map('trim', $keywords));
                    }
                }

                return $terms;

        }



    }


}
